### ISSUE TITLE
Remove duplication between book-shared.js files as far as possible

### ISSUE THREAD

**Issue by nickevansuk** [openactive/openactive-test-suite#10]
Lots of duplicate code between "book-shared.js”, can we remove this duplication as far as possible? I.e. rationalise code that defines each flow and scenario to ensure maximum code reuse

**Comment by ylt** [comment]
> I.e. rationalise code that defines each flow and scenario to ensure maximum code reuse
Flows have been deduplicated in https://github.com/openactive/openactive-test-suite/pull/30

An idea is that we may be possible to further remove duplication by using shared examples. We can define the various expectations elsewhere, and include those into each test suite that require them. (i.e. we're often checking C1 responses, so can have a set of common tests for those)
