### ISSUE TITLE
Run subset of tests and address performance issues

### ISSUE THREAD

**Issue by nickevansuk** [openactive/openactive-test-suite#11]
Can we specify parameters somehow to only run some of the tests, or otherwise pipe more of the output into the log files?

For example could we add a category (e.g. "C1only", "endtoend") to each of the tests, and use parameters to run only tests in a certain category? 

The results are fairly overwhelming on first run

**Comment by nickevansuk** [comment]
Additionally the test suite currently takes around 40 seconds to startup, before it runs any tests.

It outputs `jest` and then appears to wait.

**Comment by nickevansuk** [comment]
Also we should make parallel execution of tests configurable, as this can have the effect of slowing down testing for a larger number of tests against a database

**Comment by ylt** [comment]
This is already configurable, just needs documenting. Defaults are in the package.json, and can also be changed via commandline args.
```
npm run test -- --maxWorkers 1
```

**Comment by ylt** [comment]
Running a subset of tests can be done just by specifying the test path, this can be a directory (run everything within).
```
npm run test -- test/flows/book-and-cancel
```
(run all book and cancel flows).

all the way down to specifying an individual test file:
```
npm run test -- test/flows/book-and-cancel/book-and-customer-cancel-success/book-free-test.js
```

**Comment by nickevansuk** [comment]
Ok great! Can we also use wildcards?

The usecase I'm thinking of is where we have (following discussions this morning and notes in https://github.com/openactive/openactive-test-suite/issues/34):
- `test/flows/book-and-cancel/book-and-customer-cancel-success/book-free-test-scheduledsession.js`
- `test/flows/book-and-cancel/book-and-customer-cancel-success/book-free-test-slot.js`
- `test/flows/book-and-cancel/book-and-customer-cancel-success/book-free-test-slot-and-scheduledsession.js`

and we perhaps only want to run those that only involve "ScheduledSession" (because they haven't implemented `Slot`s in their system)

Unless there's another approach we can take here?

**Comment by nickevansuk** [comment]
Need to allow a subset of the tests to be run for only `SessionSeries`, or `FacilityUse`, or both or more depending on what feeds have been implemented by the booking system

**Comment by ylt** [comment]
Trying to figure out whether we can implement some sort of filtering system - being able to define them much like rspec would be nice: https://relishapp.com/rspec/rspec-core/docs/hooks/filters

**Comment by nickevansuk** [comment]
@ylt to scope this issue down to something achievable within a reasonable timebox, could we just cover the following two in a config file:

## Configuration spec

The test suite can be configured to test "optional" features, by indicating whether they are either:
- `implemented` - the tests will run to confirm proper implementation of the feature
- `not-implemented` - the tests will run to confirm the feature is correctly advertised as "not implemented"
- `disable-tests` - disable all tests for this feature (only recommended during development)

Additionally, bookable opportunity types can be configured, to indicate which types the implementation is expected to support:
- `sessions` (dual feeds of `SessionSeries` and `ScheduledSession`)
- `facilities` (dual feeds of `FacilityUse` and `Slot`)
- `events` (feeds of `Event`)
- `headline-events` (feeds of `HeadlineEvent` with embedded `Event`)
- `courses` (feeds of `CourseInstance`)

## Configuration example

An example config file could look like this:

```
{
  "features": {
    "opportunity-feed": "implemented",
    "dataset-site": "implemented",
    "availability-check": "not-implemented",
    "simple-book-free-opportunities": "not-implemented",
    "simple-book-with-payment": "not-implemented",
    "payment-reconciliation-detail-validation": "not-implemented",
    "booking-window": "not-implemented",
    "customer-requested-cancellation": "not-implemented",
    "seller-requested-cancellation": "not-implemented",
    "seller-requested-cancellation-message": "disable-tests",
    "cancellation-window": "implemented",
    "seller-requested-replacement": "implemented",
    "named-leasing": "implemented",
    "anonymous-leasing": "implemented"
  },
  "opportunity-types": {
    "sessions": true
    "facilities": true
    "events": false
    "headline-events": false
    "courses": false
  }
}
```

## Logic example

An example of how this should work:

If `"simple-book-with-payment": "implemented"`, the following test should be run:
- within `openactive-integration-tests/test/features/core/simple-book-with-payment/implemented`

If `"simple-book-with-payment": "not-implemented"`, the following test should be run:
- within `openactive-integration-tests/test/features/core/simple-book-with-payment/not-implemented`

If `"simple-book-with-payment": "disable-tests"`
- neither tests should be run


Depending on the boolean values of `opportunity-types`, the array in the following should be populated:
- `openactive-integration-tests/test/features/payment/simple-book-with-payment/implemented/book-random-test.js`

**Comment by nickevansuk** [comment]
All the issues mentioned here have been resolved / implemented
