### ISSUE TITLE
Include other test failures in log files

### ISSUE THREAD

**Issue by nickevansuk** [openactive/openactive-test-suite#15]
Include non-validation test failures in log file, so they are all in one place

**Comment by ylt** [comment]
This is a little tricky to integrate with. Logging will need to refactored to be handled at a slightly more global level, however there are some new complexities that need figuring out.

https://jestjs.io/docs/en/configuration#globalsetup-string
> "Note: Any global variables that are defined through globalSetup can only be read in globalTeardown. You cannot retrieve globals defined here in your test suites."

So, we may very well need multiple loggers that write to the same files. This should be possible to safely do.

Approach I'm going with is to use a reporter. The reporter seems to only be invoked once the tests are done as a whole, so shouldn't have any problems with multiple writes at the same time.

---

Little investigation into the ordering of things.. (looking into whether to use a global teardown in combination with the reporter)

![openactive-integration-tests (zsh) 2020-02-19 10-25-35](https://user-images.githubusercontent.com/705668/74827354-33f72c00-5305-11ea-8aa3-f7fd0355e532.png)

("global teardown" is a script defined as the [globalTeardown](https://jestjs.io/docs/en/configuration#globalteardown-string), with the rest of the messages coming from a[ custom reporter](https://jestjs.io/docs/en/configuration#reporters-arraymodulename--modulename-options) defining the "onRunStart, onTestStart, onTestResult, onRunComplete" methods)

**Comment by nickevansuk** [comment]
As discussed on call just now - we should expand this issue to include making the presentation of the log files as useful as possible, so that they can be used instead of all the (fairly confusing) console output

**Comment by ylt** [comment]
The console output can be fully changed as well, especially with the changes I need to make.

**Comment by ylt** [comment]
At the moment, it's using the `default` reporter (the one that's showing the stack trace, etc), in combination with the `spec` reporter (the checklist).

Current plan is to make the tests output to a more predictable file path.

On completion of a test suite, have the reporter pick up that file and output a more pretty file that also includes the test status. At that point it's just a case of also console.log-ing it out. Perhaps that output is good enough then to completely disable the current reporters.

**Comment by nickevansuk** [comment]
Just to note on this one - if there are timeout issues it's not currently very obvious what's going on as stuff just starts randomly failing (C1 responses don't show up, the validator doesn't get triggered, etc)

Looking at the .json output there are messages like:
`"Timeout - Async callback was not invoked within the 15000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 15000ms timeout"`

Not sure this is a special case? Would be good to add something so the test results are shown as invalid in the output file due to a timeout for that file, or something?
