### ISSUE TITLE
Rethinking the flow-helper logic

### ISSUE THREAD

**Issue by nickevansuk** [openactive/openactive-test-suite#205]
@nickevansuk I think we could do with rethinking the flow-helper logic so that you define specific flows. e.g. we can have the default flow be `C1 -> C2 -> B`, as well as a cancellation flow which is `(default flow) -> U -> getFeedUpdate`

This way, we don't have to have things like `BAfterP` and `getFeedUpdateAfterU` and the `_stagesToSkip`. It would require a bit of work though e.g.  it might be helpful to have the "flow item" store its own state rather than request-state just having a `BResponse`.. 🤔  this would allow us to very simply have multiple getFeedUpdate responses stored (as this can happen more than once in a flow) - even something like B can happen more than once in a flow if we're testing a booking system's behaviour from multiple duplicate (or altered) bookings

_Originally posted by @lukehesluke in https://github.com/openactive/openactive-test-suite/pull/193#discussion_r496676729_

**Comment by nickevansuk** [comment]
Further thoughts from me:

> Is this primarily about figuring out which flow stage waits on what? E.g. that in some cases B depends on C2, getFeedUpdate depends on U, etc?
> 
> I wonder given the number of potential variants mean we should have defaults and "custom", where custom is declares at the top of the test, perhaps as a simple array of stages? We could then define some constants which are just pre-defined arrays e.g. `['C1', 'C2', 'B']`, `['C1', 'C2', 'B', `U`, `getFeedUpdate`]` ?
> 
> Perhaps B could then look within the array to figure out what's before it that it should be waiting on?
> 
> We also need some way of it knowing that any "get from feed" type of stage need to start before the previous stage (to collect whatever result from it), perhaps we just do that by convention? So `get*` will always start before the previous stage?)
> Also some tests are `['GetMatch', 'C1', 'C2', 'B', 'GetMatch']`

**Comment by lukehesluke** [comment]
@nickevansuk 

> Is this primarily about figuring out which flow stage waits on what?

Yes

How about, using the cancellation example..:

```js
> const flow = new FlowHelper(state, {
  stagesTemplate: [
    { type: 'GetMatch' },
    { type: 'C1' },
    { type: 'C2' },
    { type: 'B' },
    { type: 'U', getFeedUpdate: true }, // note that this is a stage modifier rather than its own stage
});

> flow.stageSpecs // Created in the FlowHelper constructor using the template
[{ type: 'GetMatch', identifier: '0-GetMatch' },
 { type: 'C1', identifier: '1-C1', preRequisite: <ref to GetMatch entry above> },
 { type: 'C2', identifier: '2-C2', preRequisite: <ref to C1 entry above> },
 { type: 'B', identifier: '3-B', preRequisite: <ref to C2 entry above> },
 { type: 'U', identifier: '4-U', preRequisite: <ref to B entry above>, getFeedUpdate: true }]

> const [getMatch, c1, c2, b, u] = flow.stageSpecs;

> await flow.runStage(c2); // will run getMatch, c1 & c2

> flow.getStageResult(c2);
{ state: 'response-received', response: <ChakramResponse..> }

> flow.getStageResult(b);
{ state: 'no-response-yet' }

> await flow.runStage(u); // will run b & u. Running u will kick off the feed update

> flow.getStageResult(u);
{ state: 'response-received', response: <ChakramResponse..>, feedUpdateResult: <ChakramResponse..> }

// alternatively, if the feed update didn't seem to happen (e.g. timeout waiting for the feed
{ state: 'response-received-but-no-feed-update', response: <ChakramResponse..> }
```

This allows duplicate stage types (e.g. double GetMatch). The stageSpec identifier (e.g. `3-B`) is used to get the stageResult. Since this identifier includes the position of the stage within the array, there can be duplicates with different results.

And it has a way of handling the "get feed update" behaviour, which I think is a bit different from a separate stage, hence it's a modifier on a stage.

Because the results are stored in the flow-helper though, this would change a few things and reduce the role of RequestState

Lmkwyt!

**Comment by nickevansuk** [comment]
Yes interesting!

One small challenge here is that "GetMatch" is not really a stage...

If it was run after e.g. B it would need to be run with [`?useCacheIfAvailable=false`](https://github.com/openactive/openactive-test-suite/blob/1d904dea88d0a628bb810db533a8417eab7600eb/packages/openactive-integration-tests/test/helpers/request-helper.js#L246-L246), which would need to be requested before the call to B took place (in the same way as the Orders Feed call is made before U takes place.

So perhaps we have `getOrdersFeedUpdate: true` and `getOpportunityFeedUpdate: true`?

**Comment by lukehesluke** [comment]
> So perhaps we have getOrdersFeedUpdate: true and getOpportunityFeedUpdate: true?

👌

**Comment by nickevansuk** [comment]
I guess things like `opportunityFeedExtractResponses` would still stay in RequestState? Or maybe elsewhere? Perhaps there's an interesting discussion here about what the role of RequestState and FlowHelper actually both are?

**Comment by lukehesluke** [comment]
> Also some tests are ['GetMatch', 'C1', 'C2', 'B', 'GetMatch']

@nickevansuk do you have any examples of where GetMatch is needed twice in a flow?

**Comment by nickevansuk** [comment]
Sure, for leasing:
- For an opportunity with 2 spaces: Check the opportunity has 2 spaces in the feed. Run C1 to book one item (creating an anonymous lease). Check the opportunity has 1 space in the feed.
- Flow 1: `GetMatch, C1, GetLatestMatch`

Also for leasing:
- Calling C2 should decremented the remaining remainingAttendeeCapacity in the feed by 1, however a subsequent call to C2 should include remainingAttendeeCapacity unchanged in the response for the same UUID, and remainingAttendeeCapacity decremented by 1 for a new UUID
- Flow 1: `GetMatch`
- Flow 2: `C1, C2, GetLatestMatch, C2, GetLatestMatch`
- Flow 3: (new UUID, same opportunities): `C1, C2`

* where `GetLatestMatch` uses `?useCacheIfAvailable=false` as above

**Comment by lukehesluke** [comment]
Interesting. Yeah I definitely see your point about labelling them differently. So the very first `GetMatch` is "get me **some** opportunities that match an opportunity criteria (and use the cache)" and the `GetLatestMatch` is "wait for these opportunities that have already been selected to re-appear in the opportunity feed".

I definitely agree with your earlier point that `GetLatestMatch` should be modifier `getOpportunityFeedUpdate: true`

Thanks, that's helpful! (and let me know if I misunderstood anything here)

**Comment by nickevansuk** [comment]
Yep, minor nuance that `GetMatch` doesn't actually get the opportunities that match the criteria (that's what `await state.fetchOpportunities(orderItemCriteria);` does). Rather `GetMatch` gets the latest extract of the selected items from the feed, and `GetLatestMatch` / `getOpportunityFeedUpdate: true` waits for the feed to be updated _following the previous call_ (and will timeout otherwise).

So for `GetMatch` the data has already been cached from somewhere way back in the feed. For `getOpportunityFeedUpdate` the data _must_ come from a fresh item in the feed, which is expected to have been generated by the previous call.

**Comment by lukehesluke** [comment]
This is complete
