### ISSUE TITLE
Refactor in-memory database to allow all bookable types to be stored

### ISSUE THREAD

**Issue by nickevansuk** [openactive/openactive-test-suite#21]
Refactor ScheduledSessions and SessionSeries in-memory database to “Opportunity” and “OpportunityParent”, and ensure that it pulls from multiple feeds, e.g. FacilityUse (OpportunityParent) and Slot (Opportunity) based on test data here https://opendata.fusion-lifestyle.com/OpenActive/

See here for different types:
https://developer.openactive.io/publishing-data/data-feeds/types-of-feed#event-relationship-overview

**Comment by nickevansuk** [comment]
@ylt the changes required for this were actually pretty straightforward, so have done these in https://github.com/openactive/openactive-test-suite/commit/07849a1e1564b2e87bf7052679b0601bdd725179

You can simply use a `type` parameter with `/get-random-opportunity` as follows to get a random opportunity of the appropriate type:
```
http://localhost:3000/get-random-opportunity?type=ScheduledSession
```

Hopefully this should easily unblock #34 if one was a prereq for the other?

**Comment by ylt** [comment]
@nickevansuk oh perfect, thanks a lot. Was wondering why this was further down the list.
