### ISSUE TITLE
customer-details-capture-identifier - customer-identifier-capture - C1, C2 and B - identifier is reflected back

### ISSUE THREAD

**Issue by NemanjaStefanovic** [openactive/openactive-test-suite#212]
**Feature**

Support for capturing Customer Identifier. Note these fields cannot be mandatory.

**Use Case**

Describe the use case to test

Customer Identifier supplied by Broker should be reflected back by booking system.
[Open Booking API spec](https://www.openactive.io/open-booking-api/EditorsDraft/#schema-person-for-customer-or-attendee).

**Comment by lukehesluke** [comment]
This has been completed
