### ISSUE TITLE
 Output a test result certification zip file

### ISSUE THREAD

**Issue by nickevansuk** [openactive/openactive-test-suite#26]
The integration tests should include a script entry in the package.json to output a single Test Result Certification Zip File, which is a zip file containing all test results in a well-defined structure. This script must use only npm dependencies (e.g. gulp, and gulp-zip), and not rely on the local operating system to create the zip, to maximise compatibility.

In addition to containing the console output and log files (as evidence of the requests and responses from the implementation under test), the zip file should contain a machine-readable version of the results, to allow a separate service to easily verify that all tests pass.

**Comment by thill-odi** [comment]
Deferred.
