### ISSUE TITLE
Clean up logging

### ISSUE THREAD

**Issue by nickevansuk** [openactive/openactive-test-suite#46]
- Joe to reduce the size of the titles and clean up logging
- Joe to create a new PR to output errors alongside items

**Comment by ylt** [comment]
Getting there:
![openactive-integration-tests (zsh) 2020-03-11 09-49-02](https://user-images.githubusercontent.com/705668/76403934-9334e300-637d-11ea-8d07-167e3d610573.png)
![openactive-integration-tests (zsh) 2020-03-11 09-49-30](https://user-images.githubusercontent.com/705668/76403980-a5168600-637d-11ea-96f5-e676e2e1fe4d.png)

**Comment by nickevansuk** [comment]
Now much improved
