### ISSUE TITLE
Test suite not running on Linux

### ISSUE THREAD

**Issue by nickevansuk** [openactive/openactive-test-suite#473]
Threading issues are apparently preventing the test suite from running on Linux (Ubuntu 20.04).

Solution is to use a better threading library.

**Comment by lukehesluke** [comment]
I have also seen this issue on a Linux machine

# What happens

1. Run broker
2. Broker Harvests all feeds and then logs that there are validation errors:
3. Open the validation errors page and see this issue:

```
Validation Library Error
Timeout: Did not receive an init message from worker after 10000ms. Make sure the worker calls expose().
```

# The issue

As Nick pointed out, this happens as a result of the `validator-worker.js` validator worker threads (which are spawned by `AsyncValidatorWorker`) not being able to initialise in Linux. Not sure exactly why though

**Comment by nickevansuk** [comment]
I've also seen this on MacOS under heavy load, so it seems to be some kind of race condition? Perhaps the application running locally under test uses resources intensely it could cause the issue on any platform? (in my report above there were several docker containers running on the machine that produced the error)
