### ISSUE TITLE
Allow user to configure which features should be tested

### ISSUE THREAD

**Issue by thtg88** [openactive/openactive-test-suite#50]
The API specification has many features not all of which are required to be be implemented in order to be conformant.

The user should be able to say whether each feature is `implemented`, `not-implemented` or `disable-tests`. The behaviour of the tests should match this configuration.

In the case of `not-implemented` the tests will check it is actually not implemented (rather than ignoring, that's the `disable-tests` case).

How the user can adjust this configuration and the effects of each mode must be documented.

See https://github.com/openactive/openactive-test-suite/tree/master/packages/openactive-integration-tests/test/features#testing-scope and https://github.com/openactive/openactive-test-suite/issues/11#issuecomment-603793885 for more information.

Config could look like:
```json
"features": {
    "opportunity-feed": "implemented",
    "dataset-site": "implemented",
    "availability-check": "not-implemented",
    "simple-book-free-opportunities": "not-implemented",
    "simple-book-with-payment": "not-implemented",
    "payment-reconciliation-detail-validation": "not-implemented",
    "booking-window": "not-implemented",
    "customer-requested-cancellation": "not-implemented",
    "seller-requested-cancellation": "not-implemented",
    "seller-requested-cancellation-message": "disable-tests",
    "cancellation-window": "implemented",
    "seller-requested-replacement": "implemented",
    "named-leasing": "implemented",
    "anonymous-leasing": "implemented"
  },
```

Depends on:
* Re-organize folder structure, including logger changes [#57]
* Add user-defined configuration to test suite [#58]

Related:
* Add more tests [#56] - these contain actual examples of non-implemented tests.

Subtasks: 
- [ ] Add per-feature option to configuration
- [ ] Determine which test flows to run based on configuration
- [ ] Document for user how to configure behaviour for each feature and the list of available features

**Comment by henryaddison** [comment]
See also https://github.com/openactive/openactive-test-suite/issues/11#issuecomment-603793885

**Comment by henryaddison** [comment]
Some related subtasks:
* Remove flows folder from feature folder structure of tests
* Library of checks - More than just success checks
* Specify not-implemented tests
* Implemented & not-implemented switch
* When not implemented test is not present, tests should still run (possible with a no-op pass)

**Comment by henryaddison** [comment]
TODO: create separate issues for subtasks in description and add issues for each of the feature tests.

**Comment by nickevansuk** [comment]
Included in test.json
