### ISSUE TITLE
Run each test using pairs of items of different opportunity type as the test data

### ISSUE THREAD

**Issue by thtg88** [openactive/openactive-test-suite#54]
It is not enough just to check that the API behaves when all items are other the same order type. Instead there must be test cases covering pairs of order items where the items for different type.

These must cover each possible pairing of available opportunity types (so based on 5 possible types, that's 10 pairs, 5 Choose 2)

Depends on:
- Supporting multiple types of event [#51]
- Using more than one event at a time in a test [#53]

Subtasks:

- [ ] When running each test, use pairs of each type of opportunity as the test events data.

**Comment by nickevansuk** [comment]
This is now handled by the FeatureHelper
