### ISSUE TITLE
Ensure idempotency is tested properly by test suite

### ISSUE THREAD

**Issue by nickevansuk** [openactive/openactive-test-suite#575]
The idempotency test stops short of actually testing full idempotency. It should be quick to resolve this:

1. [x] Add a check in the test suite idempotency tests that have been recently added to ensure that the B response from the first B call is deeply equal to the B response from the second B call
2. [x] Once merged, merge master into ~~https://github.com/openactive/openactive-test-suite/pull/553~~ https://github.com/openactive/openactive-test-suite/pull/597 to regenerate the Docker image to include these tests too

**Comment by lukehesluke** [comment]
> [x] Once merged, merge master into https://github.com/openactive/openactive-test-suite/pull/597 to regenerate the Docker image to include these tests too

This has now been done
