### ISSUE TITLE
Read Feed URLs from dataset site, and ensure appropriate error is thrown and displayed if dataset site is invalid

### ISSUE THREAD

**Issue by henryaddison** [openactive/openactive-test-suite#59]
https://github.com/openactive/data-models/blob/master/versions/2.x/meta.json#L9

Read from dataset site in order to receive URL configuration of feeds, using the “parent” attribute of https://github.com/openactive/data-models/blob/master/versions/2.x/meta.json#L9 to automatically infer “Opportunity” and “OpportunityParent”

What is an OpportunityParent? In fact what is an Opportunity?
See the 'Bookable Objects in the Model' diagram on p. 3 here: https://docs.google.com/document/d/1mo_N1xa0H9D4uVEz3m8kyCPAAXcSEjwpEiv995hDxQs/edit#. Opportunities are the bottom row; their parents are the top (in humanspeak, an Opportunity is an 'opportunity to exercise')

**Comment by ylt** [comment]
What purpose does the meta.json serve here?
From the task description, I'd expect it to be purely to
* Pull down datafeed site (i.e. https://sw-oa-ruby-test-site.herokuapp.com/)
* Extract the JSON-LD document (using something like Cheerio)
* Parse it
* Use the `distribution` section to pull down all bookable types (i.e. from the above page,
```
    "distribution": [{
      "@type": "DataDownload",
      "name": "SessionSeries",
      "additionalType": "https://openactive.io/SessionSeries",
      "encodingFormat": "application/vnd.openactive.rpde+json; version=1",
      "contentUrl": "https://sw-oa-ruby-test-site.herokuapp.com/feed/session-series"
    }],
```
)

What extra does the meta.json add here?

**Comment by nickevansuk** [comment]
This has been implemented
