### ISSUE TITLE
Revert "Revert "Update data models" "

### ISSUE THREAD

**Issue by civsiv** [openactive/openactive-test-suite#598]
When this issue (https://github.com/openactive/OpenActive.Server.NET/issues/213) is complete, could you revert this revert in Test Suite: https://github.com/openactive/openactive-test-suite/pull/581. This will bring Test Suite up to date with Data Models changes

**Comment by lukehesluke** [comment]
This no longer needs to be done as data-models is now at v2.0.316 in Broker 👍
