### ISSUE TITLE
Set request headers as for booking calls via a JSON object in Feed Listener

### ISSUE THREAD

**Issue by henryaddison** [openactive/openactive-test-suite#60]
Such as making X-OpenActive-Test-Client-Id configurable, and add configuration for X-OpenActive-Test-Seller-Id (and any others that the user wants to set).

How is seller id related to rpdeItem.data.superEvent.organizer["@id"]?
That's what seller id is currently set to in test suite

**Comment by nickevansuk** [comment]
Request headers are now part of config
