### ISSUE TITLE
Improve error pages of test suite results - better format and navigation (potentially make them HTML to expand and contract detail?)

### ISSUE THREAD

**Issue by civsiv** [openactive/openactive-test-suite#627]
Include a "jump to first error" link

Also collapse details related to successful steps, so the page is shorter to scroll through

Include a button that uncollapses all the headings.

Include summary page being HTML-ified.

Include a markdown-to-css library (if necessary, better to use Bootstrap). Note that these markdown elements will need to be converted to HTML: code blocks and horizontal lines.

Two handlebars files to edit:

- https://github.com/openactive/openactive-test-suite/blob/master/packages/openactive-integration-tests/test/report-templates/report.md.handlebars

- https://github.com/openactive/openactive-test-suite/blob/master/packages/openactive-integration-tests/test/report-templates/summary.md.handlebars

Use bootstrap or similar external CSS reference (that includes code blocks etc.)

E.g. `document.querySelector('div#layer1').style.display = 'none'`

Ensure any markdown in https://github.com/openactive/openactive-test-suite/blob/master/packages/openactive-integration-tests/test/report-generator.js is also converted to HTML

**Comment by lukehesluke** [comment]
Is blocking https://github.com/openactive/openactive-test-suite/issues/607 presently as this will need to update test output somewhat
