### ISSUE TITLE
Update Broker Microservice to support "Bigint" for `modified`

### ISSUE THREAD

**Issue by nickevansuk** [openactive/openactive-test-suite#632]
This allows it to work with https://github.com/openactive/OpenActive.Server.NET/issues/219

See further documentation here: https://developer.openactive.io/using-data/harvesting-opportunity-data#storing-rpde-modified-with-less-than-64-bit-integers

**Comment by lukehesluke** [comment]
Apologies, this is the latest perspective on dealing with big ints: https://github.com/openactive/data-model-validator/issues/439#issuecomment-1795726091
