### ISSUE TITLE
Address performance issues

### ISSUE THREAD

**Issue by henryaddison** [openactive/openactive-test-suite#65]
Extracted from #11 

> Additionally the test suite currently takes around 60 seconds to startup, before it runs any tests.
> 
> It outputs jest and then appears to wait for 30 seconds, before outputting Found 7 test suites and then waiting for a further 30 seconds.
> 
> Can we improve performance here? What are we doing to slow things down?

May be fixed by making parallel execution of tests configurable, as this can have the effect of slowing down testing for a larger number of tests against a database:

> This is already configurable, just needs documenting. Defaults are in the package.json, and can also be changed via commandline args.
> 
> npm run test -- --maxWorkers 1

**Comment by henryaddison** [comment]
Take care as a lot of test cases are about to be added so maybe hold off on this until they are complete (#51, #52, #53 , #54)

**Comment by nickevansuk** [comment]
Removing babel seems to have made significant improvements, and `npm test --runInBand` is now well documented
