### ISSUE TITLE
Document how to run a subset of tests

### ISSUE THREAD

**Issue by ylt** [openactive/openactive-test-suite#66]
Extracted from #11.

Document how to use jests own path filtering based on the new folder structure once #57 is done.

---

NB Other ways to change which tests to run (including their documentation) are covered by the following issues:
- how to configure which features should be tested - #50 
- how to configure activity types - #51 
    - \+ note that activity types need to be in the dataset - #59

**Comment by nickevansuk** [comment]
This is now part of the general documentation
