### ISSUE TITLE
Add core/availability-check tests

### ISSUE THREAD

**Issue by henryaddison** [openactive/openactive-test-suite#68]
Child of #56

# Tests when feature is marked as implemented

- Given an known opportunity that can be booked
  When running C1 and C2
  Then the values in the responses from the requests should match the known values of the opportunity

- Given an opportunity that is not bookable
  When running C1 and C2
  Then an OpportunityOfferPairNotBookableError should be returned

- Given an unknown opportunity (fictional identifiers)
  When running C1 and C2
  Then expect an UnknownOpportunityDetailsError error to be returned

# Tests when feature is marked as not-implemented

An no-op failing tests because feature is required.

**Comment by henryaddison** [comment]
@nickevansuk Could you confirm for us that items will start appearing in the order feed (and return from the get-order endpoint) once C1 and C2 have been called? We've only ever checked the order feed using get-order after B has been run as well.

**Comment by nickevansuk** [comment]
These checks should not need to touch the orders feed, as they won't have any affect on it

**Comment by henryaddison** [comment]
Description updated
