### ISSUE TITLE
Add payment/payment-reconciliation-detail-validation tests

### ISSUE THREAD

**Issue by henryaddison** [openactive/openactive-test-suite#71]
Child of #56

# Tests when feature is marked as implemented

Given an opportunity that requires Payment Details being supplied (regex match name, fallback to bookable)
When using accountId "TEST" (**NB this value should be configurable**)
Then running C1, C2 and B should succeed

Given an opportunity that requires Payment Details being supplied (regex match name, fallback to bookable)
When excluding accountId
Then running C1, C2 and B should fail with InvalidPaymentDetailsError

# Tests when feature is marked as not-implemented

None

# Depends on
- Existance of user-defined configuration system #58

**Comment by henryaddison** [comment]
@nickevansuk Does the .net booking system we're running against support accepting bookings when accountId is "TEST" already? I guess this something that all booking systems will need to support so ought to add to the documentation for booking system developers trying to use this tool.

Also should the accountId be hard-coded to "TEST" or should it be made configurable?

**Comment by nickevansuk** [comment]
Great point @henryaddison - of the two running .NET instances, one supports only "STRIP" and the other doesn't support this (i.e. they would configure this test to be "not implemented"). 

So yes the string "TEST" should be made configurable
