### ISSUE TITLE
Add restriction/booking-window tests

### ISSUE THREAD

**Issue by henryaddison** [openactive/openactive-test-suite#72]
Child of #56

Check [documentation](https://www.openactive.io/open-booking-api/EditorsDraft/#definition-of-a-bookable-opportunity-and-offer-pair) for info on Opportuntity-Offer pairs

# Tests when feature is marked as implemented

Given an Opportunity and Offer pair with Opportunity's startDate in range of validFromBeforeStartDate of the Offer
When running C1 and C2
Then it should succeed

Given an Opportunity and Offer pair with Opportunity's startDate outside of range of validFromBeforeStartDate of the Offer
When running C1 and C2
Then it should fail with Error [exact error TBC]

# Tests when feature is marked as not-implemented

None

**Comment by henryaddison** [comment]
Unsure what the fields in the description of the test events are

**Comment by nickevansuk** [comment]
Have updated the issue description above to make clearer

Worth noting that whenever you book something you always need an [Opportunity and Offer **pair**](https://www.openactive.io/open-booking-api/EditorsDraft/#definition-of-a-bookable-opportunity-and-offer-pair), so the test will have to select the relevant Offer to run with from those available.

**Comment by henryaddison** [comment]
Yes, I think slackness with using opportunities to mean events and offers implicitly in relation to booking has got me in trouble.

**Comment by henryaddison** [comment]
@nickevansuk and just to be clear validFromBeforeStartDate is a property on the Opportunity then and startDate on the Offer?

**Comment by nickevansuk** [comment]
Other way around:
- `validFromBeforeStartDate` is a property on the `Offer`, and `startDate` on the `Opportunity`
