### ISSUE TITLE
Add cancellation/order-deletion tests

### ISSUE THREAD

**Issue by henryaddison** [openactive/openactive-test-suite#73]
Child of #56

These tests are to ensure Order Deletion flow step is used in tests as well as implemented in #42 

# Tests when feature is marked as implemented

Given any known opportunity that can be booked
When running C1, C2 and B and checking Orders feed for Order to then run U and then Order Deletion
Then should find a new entry in Orders Feed to say event is deleted

# Tests when feature is marked as not-implemented

No-op failure (required feature)

**Comment by henryaddison** [comment]
@nickevansuk When the order is deleted, does the order feed get an new entry to say it's deleted? Rather than it disappearing from the feed. Checking to know whether the test will be able to check for something rather than the lack of an entry.

**Comment by nickevansuk** [comment]
Yep it must get a new entry to say deleted, so can be explicitly checked for
