### ISSUE TITLE
Add cancellation/seller-requested-cancellation tests

### ISSUE THREAD

**Issue by henryaddison** [openactive/openactive-test-suite#75]
Child of #56

# Tests when feature is marked as implemented

Given event which matches regular expression or is bookable
When an event is booked
Then the seller cancelling it should succeed and should find entry in orders feed to say the order is cancelled 

# Tests when feature is marked as not-implemented

None

**Comment by henryaddison** [comment]
@nickevansuk is the seller-cancellation test interface already implemented in the .net booking system?

**Comment by henryaddison** [comment]
@nickevansuk are there any checks that should be done after the seller cancellation has occurred other than the call succeeding?

**Comment by nickevansuk** [comment]
yes, once seller cancellation has occurred the Orders Feed should show the Order with the OrderItem set to `https://openactive.io/SellerCancelled`

`seller-cancellation` test interface is not implemented in .NET, but will be by the time you come to do this
