### ISSUE TITLE
Add logic for picking events for random test mode to microservice

### ISSUE THREAD

**Issue by henryaddison** [openactive/openactive-test-suite#77]
Add logic for picking random events to the microservice (not the test suite). The test suite can then just asks microservice for an event meeting particular criteria (e.g. the one called foo and the microservice will do the work to return it).

If an event matching the criteria cannot be found, then a specific error should be raised in the test.

Also desire fallbacks in some cases when picking an event from feed. e.g. Event which matches regular expression or is bookable.

TODO: Extract from the tests for #56 what picking logic is required.

**Comment by henryaddison** [comment]
Does there need to be locking for randomly chosen events to avoid multiple parallel tests trying to use the same event in incompatible ways?

**Comment by henryaddison** [comment]
Is the picking nam-based or fixed selectors or full on querying?

**Comment by nickevansuk** [comment]
Locking is a really good point!

The idea we'd discussed was that in the microservice there would be a big case statement based on the "name" of the activity, defined in the mircoservice, something like:

Predefined rules:
 -  [All bookable filters]
   - `availableChannel` of the Offer **does** include `https://openactive.io/OpenBookingPrepayment`
   - Others from https://www.openactive.io/open-booking-api/EditorsDraft/#definition-of-a-bookable-opportunity-and-offer-pair

CASE "known-opportunity-bookable"
  - Match rules:
     - [All bookable filters]

CASE "known-opportunity-not-bookable"
  - Match rules:
     - `availableChannel` of the Offer **does not** include `https://openactive.io/OpenBookingPrepayment`

CASE "known-opportunity-bookable-no-spaces"
  - Match rules:
     - [All bookable filters]
     - `availableChannel` of the Offer **does** include `https://openactive.io/OpenBookingPrepayment`
     - `remainingAttendeeCapacity` == 0

CASE "known-opportunity-bookable-prepayment-unavailable-price-zero"
  - Match rules:
     - [All bookable filters]
     - `Offer.price` == 0
     - `prepayment` is `https://openactive.io/Unavailable` or unspecified

CASE "known-opportunity-bookable-prepayment-unavailable-price-zero"
  - Match rules:
     - [All bookable filters]
     - `Offer.price` == 0
     - `prepayment` is `https://openactive.io/Unavailable` or unspecified

**Comment by henryaddison** [comment]
DECISION: For locking, keep it simple: use timeouts and have microservice keep track of which ones have been changed/acted on/used recently (dirty) to avoid re-use across a run of all the tests. Have buckets for each case and on ingestion events get added to the buckets it matches (and remove them if they stop matching the bucket's criteria). Events in the bucket are marked as dirty when a test uses them. Have opportunity id => session id map to record which opportunities are in use by a test run session.

But how to avoid running out of events? As events will change and not be rolled back with the test runs. Rely on booking system developer to pre-populate sufficient events? Or booking systems need to add a setup hook that booking system can use to setup events (up to the booking system developers to decide what to do) and the test suite will call it (if configure).
DECISION: Docs suggestion to use curl/wget to call their own endpoint before test run if needed, rather than test attempting to call anything.

Can we work out how many events will be needed ahead of running the tests? An upper bound. Could search for each event search case used and use that to tell booking system dev what events they will need. Or use the the list of test data required for each test run to compute it.
DECISION: Or if a test can't find a suitable unused event, then fail the test.
DECISION: separate task: attempt to work out how many events were used by the last run and report on it. TODO: add this new task.

**Comment by nickevansuk** [comment]
This was updated a while back
