### ISSUE TITLE
Document which events should be in the feed already for the random tests to work

### ISSUE THREAD

**Issue by henryaddison** [openactive/openactive-test-suite#78]
Child of #56

When running a test in random mode, it will need to look up particular sorts of events in the feeds. It should be documented for a booking system developer what events they will need to populate their feed with in order for the tests pass (I guess on a per-feature/per-test event).

Can use the logic in the tests for creating events in controlled tests as examples.

NB this should including retrospectively adding this documentation for existing tests and ensuring it is added for each new test added in the other subissues of #56.

**Comment by nickevansuk** [comment]
Now included in https://github.com/openactive/openactive-test-suite/blob/master/packages/openactive-integration-tests/test/features/README.md
